### ISSUE TITLE
Task scheduling

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#114]
- [ ] Remove the scheduler app and existing routes, etc. (The task scheduling will be built into the core app)
- [ ] Evaluate scheduling libraries, both django specific and general python stuff (rolling our own is an option)
- [ ] Recurring date / time options at a minimum (Full on cron style would be a bonus)
- [ ] Models to store the schedule info
- [ ] Backend django management command that handles creating new tasks based on the scheduled jobs
- [ ] UI for managing schedules

**Comment by xeonneon** [comment]
This Celery project seems to be what we are looking for: https://github.com/celery/django-celery-beat

**Comment by scott-taubman** [comment]
celery-beat could work.  We'd have to build some layers on top of it to make the schedule management something appropriate for a normal user to interact with.  But I think that's a good place to start and certainly would solve some portions of the problem for us.

**Comment by scott-taubman** [comment]
Writing down the outcomes of an out-of-band conversation on this:

- celery-beat is going to be used for the actual schedule execution portion of this.
- We need a proxy model that the user actually interacts with for setting up schedules. It would look roughly something like:
  ```python
  class ScheduledTask(models.Model):
        id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
        function = models.ForeignKey(to="Function", on_delete=models.CASCADE)
        environment = models.ForeignKey(to="Environment", on_delete=models.CASCADE)
        parameters = models.JSONField(encoder=DjangoJSONEncoder)
        creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
        schedule = models.ForeignKey(to=CronSchedule, on_delete=models.CASCADE)
        created_at = models.DateTimeField(auto_now_add=True)
        updated_at = models.DateTimeField(auto_now=True)
  ```
- We probably also need a status field for whether the schedule is active, paused (temporarily not running), or archived (permanently not running, but the entry is still there so that the Tasks created by it can still be reference it).
- It does not appear as though django-celery-beat has a concept of pausing schedules, which means "pausing" a `ScheduledTask` will likely have to result in deleting the corresponding `CrontabSchedule` entry.  If that's the case, then we need to write the crontab schedule down on the `ScheduledTask`, otherwise we'd have no way to reconstruct the `CrontabSchedule` when the `ScheduledTask` is reactivated.
- When a `ScheduledTask` instance is created, the corresponding django-celery-beat `CrontabSchedule` (or whatever the appropriate model is) instance would be created.
- The task that celery-beat is going to execute is always a simple function that just generates a `Task` for a given `ScheduledTask` id.  Something like:
  ```python
  @app.task
  def run_scheduled_task(scheduled_task_id: UUID):
      # retrieve the ScheduledTask and then use the info contained there to create a Task instance
  ```
- We need to track the `ScheduledTask` that spawned a given `Task`.  This could be a `scheduled_task` foreign key field on the `Task`.
