### ISSUE TITLE
File parameters

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#144]
Functions should be able to have "file" type parameters that take a file upload as input.

Without overly complicating an initial implementation, we should keep in mind that we will likely need support for different file storage backends with deployments able to select between the available backends (the two most relevant probably being database and S3-compatible).  Even if our initial implementation only supports a single backend (S3-compatible), we should at least strive to not lock ourselves out of the potential of supporting others.

Other things that will need consideration:

* How the file location gets stamped into the tasking message and how we indicate that it is a file location (as opposed to just a text field that happens to have a URL in it).
* How the file is made available to the package container (probably [signed urls](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html)).
* Updating the various package templates to handle files if necessary (may not be if it's just a signed url).

**Comment by xeonneon** [comment]
If I am understanding this right, users would be able to include files into their package image, and upload files that get added  to the task container?

Do we want to take responsibility for making the file(s) available to the container before runtime, or do we want to provide means for the user to pull the file(s) into the container during runtime?

**Comment by scott-taubman** [comment]
> If I am understanding this right, users would be able to include files into their package image, and upload files that get added to the task container?
> 
> Do we want to take responsibility for making the file(s) available to the container before runtime, or do we want to provide means for the user to pull the file(s) into the container during runtime?

The part about allowing users to "include files into their package image" isn't what this is about.  That's was already supposed to be possible, with whatever files you put in the package directory (the directory where the functions.py and package.yaml live) getting added to the image when we build it.  I see that idea got lost at some point and we're actually only copying in language specific files, so that's something we'll have to fix separately.

What this issue is about is the idea of providing a file as input to a task at runtime.  So right now all of our parameter types are things that could be represented in json.  But what if someone wanted to have a function that takes as input an image file and then does some analysis or manipulation of that?  Or any other binary file for that matter.  The idea here is to allow for that sort of file upload when tasking and then all of the machinery to make sure that the runner is able to pull down the file and mount it in to the package container when executing the task.

**Comment by xeonneon** [comment]
Ok, makes sense. 

I'd be curious if MinIO would be useful for us. Perhaps we store submitted files in MinIO, pass a task argument to the container with the URIs of the files to pull down, and a "pre-task execution" script that gets baked into all the containers checks if that argument has any values. If so, pull down all the listed files?
