### ISSUE TITLE
Add filtering support to the list views

### ISSUE THREAD

**Issue by xeonneon** [beer-garden/functionary#146]
Users should have the ability to search for particular functions or packages, rather than needing to scroll through a paginated list. Users should also have the ability to apply filters to the different list views. The filters could be datetime fields (created before/after some date), the tasks that used a particular function, the tasks executed by a particular user, etc.

**Comment by scott-taubman** [comment]
This should be done after #178.

**Comment by scott-taubman** [comment]
This should now also probably be done either after or in conjunction with #197.
