### ISSUE TITLE
Updating ScheduledTask parameters causes a delay in the task firing

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#169]
From @xeonneon:

If you update a ScheduledTask, it will not run until the Schedulers next wakeup sync. For example, if I have a task that runs every minute and I update the params of that ScheduledTask, it won't run once the current minute ends. It will run during the next minute, after the Scheduler wakes up and resyncs. I think it's only an issue for tasks that run every minute.

**Comment by xeonneon** [comment]
The fix is to reduce the `max_interval` for the `Beat` scheduler to be something less than sixty seconds.
