### ISSUE TITLE
Pagination clears out sort 

### ISSUE THREAD

**Issue by west270** [beer-garden/functionary#210]
Using `django-tables2`, the tables can sort the columns and sets the sort in the url. The pagination clears the url then sets page number. It should preserve the sort in the url. 

Should be looked at after #197 .

**Comment by scott-taubman** [comment]
With it looking likely that we're going to use bootstrap afterall, we should at least wait until we get the basics of that implemented before exploring this.  It doesn't appear to be documented, but there is a bootstrap5.html template provided with django-tables2.  We may be able to switch to using that and get all the pagination working for free.

**Comment by scott-taubman** [comment]
This is solved for us by using the pagination provided with django-tables2. Closing.
