### ISSUE TITLE
API exception handler fails on non-field errors

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#219]
The `custom_exception_handler` in `core/api/exceptions.py` will itself throw an exception when handling non-field errors.  This is because it assumes that `response.data` will be a dict-like object, when it can in fact also be a list.  We'll need to update the check before setting the code to include `isinstance(response.data, dict)`

**Comment by xeonneon** [comment]
Added fix in #215 

Seems that missing field errors are the easiest way to trigger this error. Probably need a follow on task to improve the missing field errors for the API

**Comment by scott-taubman** [comment]
#215 Merged.  This is complete.
