### ISSUE TITLE
Add Fixtures for Bootstrapping Functionary Users, Teams, and Environments

### ISSUE THREAD

**Issue by xeonneon** [beer-garden/functionary#79]
When deploying Functionary for the first time, the UI expects some data to already be present, such as a user, team, and environment. By adding fixtures, we can bootstrap an admin user, dev team/environment, so that the user does not need to exec into the Functionary-django container,  `createsuperuser`, and manually create the teams/environments themselves.

**Comment by scott-taubman** [comment]
As part of this effort, it would be nice to add a "bootstrap" VSCode task that runs the migrations and loads the fixtures so that there's an easy way to get a fully functioning environment from scratch.
