### ISSUE TITLE
Team / environment level environment variables (secrets)

### ISSUE THREAD

**Issue by scott-taubman** [beer-garden/functionary#94]
- [x] #118
- [x] #121
- [x] #126

**Comment by kvig** [comment]
Q&A on the implementation:
1. Add a variables section to `package.yaml` to declare which ones you need
  - Yes, I agree. In addition to letting us limit which environment variables we pass through during tasking (which probably doesn't buy us a ton, but we may as well do if we have the info), it allows us to warn if there's a situation where a function requires a certain variable that isn't set for the environment.
2. Masking may be complicated - gitlab has a bunch of restrictions/qualifications (Secret qualifications from initial implementation: https://gitlab.com/gitlab-org/gitlab-foss/-/issues/13784/#note_106756757)
  - We don't necessarily have to bog ourselves down with trying to figure out the masking out of the gate. But we can talk about a simple-ish approach and if it buys us to implement such a thing early on or not.
3. Are variables associated with a team or an environment or both? Should an environment inherit all team variables?
  - Both. Environments inherit the Team level variables, but can override.
4. Should we allow overriding a variable on the tasking form?
  - That could be a valid requirement, not going to implement for this set of tickets
5. Have a config setting for variables you can't set(don't override `PATH`?)
  - Having a set of "reserved" environment variables that can't be set probably makes sense, but feels less important if we're making people declare in the package.yaml what environment variables to pass through. Meaning, with the explicit declaration it's not like someone settings a `PATH` variable at the team level is just going to break every package. Only packages that declare that variable would actually get it, so a proper warning in the developer docs should be sufficient.
